# Generated by Django 4.2.1 on 2023-05-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socnet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
